# nx graph variables
NUM_NODES: 8
EDGES_PROBS: 0.4
SEED: 42
DRAW_GRAPH: true

# QAOA variables
QAOA_LAYER_DEPTH: 2
STEPS: 50
SIMULATOR: "qulacs.simulator"
QAOA_LAYER_PARAMS:
  - 0.888471911491884
  - 0.5229115865472947
  - 0.7562095319286685
  - 0.9829594308722803

# Other configs
LOGS_FILE: "logs/logs.csv"
